version: "3.8"

services:
  mariadb:
    image: mariadb:11.4
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dummy
      MYSQL_USER: local
      MYSQL_PASSWORD: local
    ports:
      - "3306:3306"
    volumes:
      - ./mariadb:/var/lib/mysql
