spring:
  application:
    name: execution-service
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:mariadb://localhost:3306/dummy
    username: local
    password: local
    driver-class-name: org.mariadb.jdbc.Driver
  threads:
    virtual:
      enabled: true
